apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: spring-backend
spec:
  name: "Spring Backend"
  systemName: "springbackend1"
  privateBaseURL: "PRIVATE_BACKEND_URL"
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: spring-product
spec:
  name: "Spring Product 1"
  systemName: "springproduct1"
  backendUsages:
    springbackend1:
      path: /
