apiVersion: v1
data:
  admin_password: cmVkaGF0
kind: Secret
metadata:
  name: redhat-admin-secret
---
apiVersion: v1
data:
  admin_password: cmVkaGF0
kind: Secret
metadata:
  name: redhat-dev-secret
---